nodeLinker: pnp

packageExtensions:
  '@primevue/core@*':
    peerDependencies:
      '@primeuix/styles': '*'
  '@primevue/icons@*':
    peerDependencies:
      '@primeuix/styles': '*'
  '@vue/test-utils@*':
    dependencies:
      '@vue/server-renderer': '*'
    peerDependencies:
      '@vue/compiler-dom': '*'
