nodeLinker: pnp

packageExtensions:
  "@vue/test-utils@*":
    peerDependencies:
      "@vue/compiler-dom": "*"
    dependencies:
      "@vue/server-renderer": "*"
  "@primevue/core@*":
    peerDependencies:
      "@primeuix/styles": "*"
  "@primevue/icons@*":
    peerDependencies:
      "@primeuix/styles": "*"
